---

- name: install docker engine ubuntu
  hosts: all
  vars:
    YQ_VERSION: "4.16.2"
    YQ_BINARY: "yq_linux_amd64"

  

  become: true
  become_method: sudo

  tasks:
    - name: 1. Update the apt package index and install packages to allow apt to use a repository over HTTPS
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
          - awscli
        state: latest
        update_cache: true

    - name: 2. Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: 3. Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable  # FIXME move to var
        state: present

    - name: 4. Install docker engine
      apt:
        name: 
          - docker-ce
          - docker-compose
        state: latest
        update_cache: true
    
    # YQ

    - name: 5. Download YQ
      get_url:
        url: "https://github.com/mikefarah/yq/releases/download/v{{ YQ_VERSION }}/{{ YQ_BINARY }}"
        dest: /usr/bin/yq
        mode: '0555'

    # Docker post-install steps for ubuntu

    - name: 1. Make sure that group "docker" exists
      group:
        name: docker
        state: present

    - name: 2. Add aws user to docker docker group
      user:
        name: ubuntu
        groups: docker
        append: true
    
    # prepare docker-compose
    - name: 5. Download compose file
      get_url:
        url: https://github.com/karma-git/cicd_ec2/blob/master/app/docker-compose.yml
        dest: /home/ubuntu
        mode: '0554'

    # not working with ansible 2.9.6
    # - name: Restart services
    #   community.docker.docker_compose:
    #     project_name: cicd_ec2
    #     project_src: /home/ubuntu
    #     restarted: yes
    #   register: output
