---

name: CICD ec2

on:
  push:
    branches:
      - master
    paths:
      - 'app/**'
  create:
    tags:
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: karmawow
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        env:
          CI_COMMIT_SHORT_SHA: ${{ github.sha }}
          CI_PIPELINE_ID: ${{ github.run_id }}
          CI_COMMIT_TAG: ${{ github.ref_name }}
        with:
          context: .
          file: ./app/Dockerfile
          build-args: |
            CI_COMMIT_SHORT_SHA=${{ github.sha }}
            CI_PIPELINE_ID=${{ github.run_id }}
            CI_COMMIT_TAG=${{ github.ref_name }}
          push: true
          tags: karmawow/k8s-gitlab-ci-cd:${{ github.run_id }}
